- name: Install packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - haproxy

- name: Haproxy conf
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  vars:
    hosts: "{{ groups['kube-master'] }}"

- name: Start && enable haproxy
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - haproxy
