all:
  hosts:
    kubernetes-1:
      ansible_host: 10.0.0.105
      ip: 10.0.0.105
      # keepalived
      interface: eth0
      state: MASTER
      priority: 101
    kubernetes-2:
      ansible_host: 10.0.0.106
      ip: 10.0.0.106
      # keepalived
      interface: eth0
      state: BACKUP
      priority: 100
    kubernetes-3:
      ansible_host: 10.0.0.107
      ip: 10.0.0.107
    kubernetes-4:
      ansible_host: 10.0.0.108
      ip: 10.0.0.108
  children:
    kube-master:
      hosts:
        kubernetes-1:
        kubernetes-2:
      vars:
        # keepalived && haproxy
        router_id: 51
        auth_pass: HelloWorld!
        apiserver_vip: 10.0.0.150
        apiserver_dest_port: 8443
        apiserver_src_port: 6443
        # kubeadm
        podSubnet: 10.244.0.0/16
        caFile: /etc/etcd/ca.pem
        certFile: /etc/etcd/client.pem
        keyFile: /etc/etcd/client-key.pem
    kube-node:
      hosts:
        kubernetes-3:
        kubernetes-4:
    etcd:
      hosts:
        kubernetes-1:
        kubernetes-2:
        kubernetes-3:
    remove:
      hosts:
